Added Angular Roadmap
Ashish-khanagwal/Open-source-practice-and-resources pull request #59
Opened 2022-10-07 11:19 UTC by AdityaBansal2310

I have added Angular Roadmap. Look after that and let me know if there are some improvements.

2022-10-07 15:04 UTC, Ashish-khanagwal approved these changes
.

2022-10-07 15:04 UTC, Ashish-khanagwal commented on README.md
> +- [Angular](#angular)
Angular section has already been added to the index, delete this as well.
make sure to sync your local repo before contributing to ignore merge conflicts.

2022-10-07 15:04 UTC, Ashish-khanagwal commented on README.md
> +
don't use numbers, 
use `##` for heading and `-` to generate list

2022-10-07 15:05 UTC, Ashish-khanagwal requested changes
Hey, Some of the resources are already added to this repo, Please carefully look at the repository before adding resources.
You don't have to add HTML, CSS, and JavaScript submodules as they are also added in the repo.

2022-10-07 15:07 UTC, Ashish-khanagwal commented
@AdityaBansal2310 Please carefully look at the markdown used while adding resources and follow the instructions.

2022-10-07 15:14 UTC, Ashish-khanagwal requested changes

2022-10-07 15:14 UTC, Ashish-khanagwal commented on README.md
> +
Don't use numbers list, and use proper markdown for headings

For headings - `##`
For list - `-`

2022-10-07 19:34 UTC, AdityaBansal2310 commented
I am working on it and will make another PR by tomorrow keeping in mind all the changes you have asked to do.

2022-10-08 05:55 UTC, Ashish-khanagwal commented
So, can I close this PR, as you'll be making another PR

2022-10-08 18:08 UTC, Ashish-khanagwal requested changes
in line 258, add a line for separation
```
---
```

2022-10-08 18:08 UTC, Ashish-khanagwal commented on README.md
>      - [official website](https://angular.io/)
please remove these one line spaces in between the heading and its related resources, from the rest of your added resources

2022-10-09 08:32 UTC, Ashish-khanagwal commented
@AdityaBansal2310 you're PR not following the contribution guidelines. So, closing your PR.
If you want to contribute to this repo, please make sure to read the contribution guidelines carefully.

2022-10-09 08:32 UTC, closed without merging