Updated README.md with addition of Flutter
Ashish-khanagwal/Open-source-practice-and-resources pull request #98
Opened 2022-10-13 17:28 UTC by abhisen-exe

thanks for reading my pull request!

2022-10-13 18:09 UTC, Ashish-khanagwal requested changes
Add `Flutter resources in Cross platform section
To create a Cross-platform section into the index in alphabetical order use :point_down: 
```
- [Cross Platform Dev](#crossplatformdev)
  * [Flutter](#flutter)
```

Then create a section of Cross-platform for resources too :point_down: 
```
## Cross Platform Dev

### Flutter
```

Please make sure to add the section in alphabetical order

2022-10-13 18:28 UTC, abhisen-exe commented
The requested changes are done!

2022-10-14 04:14 UTC, Ashish-khanagwal requested changes
under line `70` (`[Core-CS](#core-cs)`) add the following code :point_down: 
```
- [Cross Platform Dev](#crossplatformdev)
  * [Flutter](#flutter)
```

2022-10-14 04:14 UTC, Ashish-khanagwal commented on README.md
> +
remove this extra empty line `211`

2022-11-10 05:29 UTC, closed without merging